eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/microservices-sound_service-web-artist
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: microservices-sound_service-web-artist-api
            client-secret: 5kcgMnheY4pPVfFmcFhVt7LBIPBx9qJx
        provider:
          keycloak:
            token-uri: http://localhost:9098/realms/microservices-sound_service-web-artist/protocol/openid-connect/token