spring:
  data:
    mongodb:
      username: hoofkhanh
      password: hoofkhanh
      host: localhost
      port: 27016
      database: artist
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8002
  
application:
  config:
    user-url: http://localhost:8222/api/users
    job-url: http://localhost:8222/api/jobs