spring:
  data:
    mongodb:
      username: hoofkhanh
      password: hoofkhanh
      host: localhost
      port: 27016
      database: conversation
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8011
  
application:
  config:
    customer-url: http://localhost:8222/api/customers
    artist-url: http://localhost:8222/api/artists