spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/hire
    username: hoofkhanh
    password: hoofkhanh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: hireConfirmation:com.hokhanh.web.kafka.HireConfirmation

server:
  port: 8008
  
application:
  config:
    customer-url: http://localhost:8222/api/customers
    job-type-url: http://localhost:8222/api/jobs
    artist-url: http://localhost:8222/api/artists