spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/job
    username: hoofkhanh
    password: hoofkhanh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8004
  
application:
  config:
    customer-url: http://localhost:8222/api/customers
    artist-url: http://localhost:8222/api/artists