spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/payment
    username: hoofkhanh
    password: hoofkhanh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: successfulPaymentNotification:com.hokhanh.web.kafka.SuccessfulPaymentNotification

server:
  port: 8007
  
application:
  config:
    purchased-beat-url: http://localhost:8222/api/purchased-beats
    hire-url: http://localhost:8222/api/hires